branch-defaults:
  master:
    environment: jonathanballandsme
global:
  application_name: jonathanballands.me
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
